version: "2.0"
services:
  worker:
    build: .
    environment:
      API_ID: $API_ID
      API_HASH: $API_HASH
      BOT_TOKEN: $BOT_TOKEN
      STRING_SESSION: $STRING_SESSION
      OWNER_ID: $OWNER_ID
      SUDO_USERS: $SUDO_USERS
      MONGO_DB_URL: $MONGO_DB_URL
      LOG_GROUP_ID: $LOG_GROUP_ID
